# Generated by Django 3.1.7 on 2021-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210403_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Email', max_length=100, null=True),
        ),
    ]
