# Generated by Django 3.1.7 on 2021-04-06 03:41

import config.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210404_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('prefix', 'PREFIX'), ('sufix', 'SUFFIX')], max_length=10)),
                ('word', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', config.db.BaseUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superhost',
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'CURRENCY_USD'), ('KRW', 'CURRENCY_KRW')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'LANGUAGE_ENGLISH'), ('kr', 'LANGUAGE_KOREAN')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=15, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Note: 사용자 프로필 추가 정보', max_length=200)),
                ('gender', models.IntegerField(choices=[(-1, 'UNKNOWN'), (0, 'MALE'), (1, 'FEMALE'), (2, 'PREFER_NOT_TO_SAY')], default=-1, help_text='Note: 성별')),
                ('date_of_birth', models.DateField(help_text='Note: 생년월일 (예 1980.12.08', null=True)),
                ('profile_url', models.CharField(blank=True, default='', help_text='Note: 사용자 프로필 Url', max_length=255, null=True)),
                ('country', models.CharField(default=None, help_text='Country code', max_length=4, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
