"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import logging

logger = logging.getLogger(__name__)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j4m0w99(g^4j0yppq)8))uuakq$%szi!#4ogq&ejjeerj#70e)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition


def ENV(variable, default=None, raise_exception=False):
    try:
        value = os.environ[variable]
    except KeyError as error:
        value = default
        if raise_exception:
            raise error
        else:
            logger.warning('Enviroment {} does not exist.'.format(variable))
    return value

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'rest_framework',
    'corsheaders',
    'django_filters'
]

PROJECT_APPS = [
    "core.apps.CoreConfig",
    "users.apps.UsersConfig",
]

INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'config.middleware.ServerMaintenanceMiddleware',
    'config.middleware.UAValidateMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DB_ALIAS_REPLICA = 'replica'
DB_HOST_REPLICA = ENV('DB_HOST_REPLICA')

DB_NAME = ENV('DB_NAME')
DB_USER = ENV('DB_USER', raise_exception=True)
DB_PWD = ENV('DB_PWD', raise_exception=True)
DB_HOST = ENV('DB_HOST', raise_exception=True)
DB_PORT = ''
DB_CONN_MAX_AGE = int(ENV('DB_CONN_MAX_AGE', default=50))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        "ATOMIC_MUTATIONS": True,
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': DB_NAME,
#         'USER': DB_USER,
#         'PASSWORD': DB_PWD,
#         'HOST': DB_HOST,
#         'PORT': DB_PORT,
#         'CONN_MAX_AGE': DB_CONN_MAX_AGE,
#         'TEST': {
#             'NAME': 'test_finance',
#         },
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': DB_NAME,
#         'USER': DB_USER,
#         'PASSWORD': DB_PWD,
#         'HOST': DB_HOST,
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

AUTH_USER_MODEL = "users.User"

CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": True,
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
    "JWT_ALLOW_ANY_CLASSES": [
        "graphql_auth.mutations.Register",
        "graphql_auth.mutations.VerifyAccount",
        "graphql_auth.mutations.ResendActivationEmail",
        "graphql_auth.mutations.SendPasswordResetEmail",
        "graphql_auth.mutations.PasswordReset",
        "graphql_auth.mutations.ObtainJSONWebToken",
        "graphql_auth.mutations.VerifyToken",
        "graphql_auth.mutations.RefreshToken",
        "graphql_auth.mutations.RevokeToken",
        "graphql_auth.mutations.VerifySecondaryEmail",
    ],
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

ACTION_LOGGER_NAME = 'action'

MAINTENANCE_HTTP_STATUS_CODE = ENV('MAINTENANCE_HTTP_STATUS_CODE', 503)
MAINTENANCE_STATUS = ENV('MAINTENANCE_STATUS', 503)
MAINTENANCE_SUBJECT = ENV('MAINTENANCE_SUBJECT', None)
MAINTENANCE_CONTENTS = ENV('MAINTENANCE_CONTENTS', None)

###########################
# DJANGO REST FRAMEWORK   #
###########################
REST_DEFAULT_AUTHENTICATION_CLASSES = (
    'config.authentication.CustomJwtTokenAuthentication',
    'config.authentication.CustomTokenAuthentication',
)

###########################
# Auth Key                #
###########################
# AUTH_SERVER_PUB_KEY = MAKE_AUTH_URL()
AUTH_SERVER_PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEAup8gRjJMk4c4vFcu8qYwnjReK13rgqDELvHbSDyuxbJL9koV
c9OGl6oETw1mbIKTsPNZOgfDJTOzHxCjmiLwWe9JlO3T7jfJpvifQIHbfZ7yXJbe
PTpE+RkzWETQXSBbC8TUCe4w0JcWAD5qKUxlab7akfJmrQDR2QYEUOFPAyi/l1UM
RtbJ4tyHQ7J8PREXeAp2I5TjlbTpEtsy2Y7BDfgBr30NSjSvn43nJw6+0dMudvlF
3i4MQLIhLfcTU7XLg7K2ZB0hovRgq7Bnx45KgruDIw18T2yVVJBAPHsyusCcGRdG
QnZzDKlhaJiUc/5UHkN2UDB3zVVZNzm2WCJheoN61VHtVGLjf45On/kggSHScMIT
4yCTwKL0VhEFf/vwSYwXC7Ft6TtWUGrl5G76+oWEXaTFDTLddu8EAln7Mu6r09dq
Fqhsd4MJBlPWTlOErGrIy3xeb/rKgFxmVdnJGynvYvZYDkks8f4M8nxBp0InRrjm
7KzwSewy0p+xMLa5UzrZkjl/xF0Sby48uSGnVdnFNEvPjBSwHMuJl3Btg+i9zi4Y
GMaNMm8otJTX0Hgrso5GyI7moqm8O0g1NhiGw2iF3fZW9Z8uoe8/Z0KebmeoUKw0
dKoxoEHRp2XWeMTcRM+uQCVJrNv8RqbPTynoWoqonFyTWehJ3IZg/Nw2b5cCAwEA
AQKCAgBsEAqDO0sGPk3HGYDQ9xS99zr0R61A9dDEEj5UxPa6+XRtCBcF+9064zMd
h3fgq3fUBgWLycThPN+ixGLHtSWSHjJwb4rBrUIyUlL86nTrd+eFX8MOlzgrOcF2
glpZIow182KI4YkYr/QIbhvREDDFG8O6sS9tTEU3Mvm6z8yN2sGeYpv6RROgLuyQ
ccDpJ4V8eCpSjjt+i8ROq+j0+2mkqhBnyrSwXHO5o1TPVAWAwJVuRQeFEQr9R2hZ
EnH5jhJrj0d4DzpT/sgfgsWFU0qoCuZznLJ31ztdPS5FF12XsEJzcPu5LpeOJGKI
S5ni1MlmwM+4vWgR2TMQ/HUu8bGZXg3mbZibXq8foHgXJmporbRr6f89wnSaFtp1
SWL5ur9YG1VB9I54SoLSaxgxqJQdHYoJzGDOQBE7HTA9iZ6typprZgoO6Jza8egB
yTAOkby+UvonUORHR9Q/n5ajeWB2fY/gDIiDhtt5HuVkni/VD4uCBLN3dU4eEujM
8uV2lyo5VJ8qKhb6uWIWsSwQAa71J4uH1bCdlr9lo2m0W9ECWwajHq4mnS85q9PI
vWp5Gr+ZxjGwTfDNWaLBy40TRvKkgTlrEd6a3pPjnPK7XWXCL9U5nzV8vW3v4gjm
r8ydbOii34YvYt1zIxUvljyoD3aqzmsxjisZ+L4T8QkclOgWmQKCAQEA8vRjZDdb
MjrF42TNr/4D+rnlP8TQ4JcPytWum7AO+iu/amHnvcDNbCiu3dmMWxNslG6NVXUM
B0Q/UNJ/uwtQdeATQKhd4mPdm0HGlJcN6qCpIn531OqDmeuKfjHHPbX7nlxpdiMC
XWOO7UR8aOe3jQ+/uy+bjFtec0AASynFvmt6EGqAnnjepHK9pAie28KZSXm36IJt
Hyr25DovyDQthHjKJaeVAaPBP7nsCOo02ennty5XCN4mn5m9F5N+euH4ij6Q2Vdo
MbpgppbX86OO24zA3xaQ9YpoQkVuJPSdW6aA/Noweh/Yn06guUkBc7Dz1E9eIaZc
CcQ/iOaR9cn2fQKCAQEAxKRkwB8weju1oSyYSa1oDrqhlCoJt+t/ovcTNG+8dHKN
CpSHYYDWGqTRaeXhcHCC/tiGZGjb5LImHAkjTWJrol6To00PAHfYEE0d3HHCf7ym
bVC6BdSlFI7Lv2pO1Xgd7spQVoVBPq4j9IjWVDCYiM0ffn+rP0q51Eg0kp2MP/y7
eKtfLMcdvJW8bsbAHaeLr63MSqKd1VsT+yJRH1BD/tFv9VqB88iQSJQQaoA0yEJJ
u13h4QOqfuDklzDAa0XM6cYn4zHipbCFhQgpGAU0OXssy6iuDKRgab/1tXS/WDJK
0kLlmdIgKkzhaQiZOXraAzfUsefKJkVcV+1DJXrWowKCAQBJIXUVgnAqA3TziLE9
S3nJK9Gsy0KQiAgR5xYi+PDZLvf0Prox7Ooop2pTjxtngsZJO6nBUnUnbsycOHCI
TdSPVr6U1NlFvwfCpx7uNTXULT4cCvNpHJo2Z6cNa1Bs6+1scqawD8OzdrdcBiRo
s28Vv+rXnnH04r/gcyBjf5RtSA67CEPk778cwwkAajPfNIlNi5znGPNd0WH1uuoN
Gl+lI3K9uN7qWm9eDknVOSJlgbnk8sbx/WSk3/MCOLx2orRccI7LTTso1NAo9PjV
9qKWxZx8yl8h+eJ+KEYKS7NeFhV3hvnWmOVsto88lpQgTeBnROixulC0A+WYAMdo
s71FAoIBAB9k24zsrdGl/L5pnzqMC8PmOeustnZ9i5gZ+B/0AtNYgnoA8og3iHci
fyh4AgDwhYloSjR3pTui0YDCWLd/Eg4PKWT15YI+n+kiVrUeGF5KYQusyrYpl91r
Ws4Ji+J61dSMyjy184+tP6JHwmgYhhG5JeENQurM5FQm3vXVX1HL6KZAPeapN28n
PLk20+8oE54NkkMMKUSp0MvUU707FE/3Yfd65qpkB9z+foxyQXsDUkAuoeRJsIun
HfehWecGcsuTzkRwb23ie76caesi0Y6nwqQVHwx3pcjcU78Pj4jmJpnhAkUHjgkS
0x3wuH27xlijLjrk9Zockrya7ZBrRx8CggEASD7dekxw7mrbXNFdbmilJdNBFG5C
WlDe2kIYwn7xZoJwLqkl7NkxuwWxWuTK2BYhtKY4xb3LqY7X/3ecRsYEPbygqKGQ
XsVg2fz1aHLNNvmcq9Db1TbGfBbDhrpvQZxcVjqbWix8J5EsX1peza1M4Gc7DBH7
4KWY21AOuG5rWU//3G8DEdrML6qvcp0jqKZbGbQF98eW6Am/EbhTMJljAGoSmZX1
ZVROG4yjlzCj5jCYH10JfvWXsS/qGtXBEG4+Ex2g1ghyYKG5vnQabm+B0R3143rf
CHMEXSyY0ogXeNBv78td7X/+pf8j68Yuze9nzldPRL7/fuZ3Yu//NGfTgA==
-----END RSA PRIVATE KEY-----
"""
AUTH_SERVER_PUB_KEY = """-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAup8gRjJMk4c4vFcu8qYw
njReK13rgqDELvHbSDyuxbJL9koVc9OGl6oETw1mbIKTsPNZOgfDJTOzHxCjmiLw
We9JlO3T7jfJpvifQIHbfZ7yXJbePTpE+RkzWETQXSBbC8TUCe4w0JcWAD5qKUxl
ab7akfJmrQDR2QYEUOFPAyi/l1UMRtbJ4tyHQ7J8PREXeAp2I5TjlbTpEtsy2Y7B
DfgBr30NSjSvn43nJw6+0dMudvlF3i4MQLIhLfcTU7XLg7K2ZB0hovRgq7Bnx45K
gruDIw18T2yVVJBAPHsyusCcGRdGQnZzDKlhaJiUc/5UHkN2UDB3zVVZNzm2WCJh
eoN61VHtVGLjf45On/kggSHScMIT4yCTwKL0VhEFf/vwSYwXC7Ft6TtWUGrl5G76
+oWEXaTFDTLddu8EAln7Mu6r09dqFqhsd4MJBlPWTlOErGrIy3xeb/rKgFxmVdnJ
GynvYvZYDkks8f4M8nxBp0InRrjm7KzwSewy0p+xMLa5UzrZkjl/xF0Sby48uSGn
VdnFNEvPjBSwHMuJl3Btg+i9zi4YGMaNMm8otJTX0Hgrso5GyI7moqm8O0g1NhiG
w2iF3fZW9Z8uoe8/Z0KebmeoUKw0dKoxoEHRp2XWeMTcRM+uQCVJrNv8RqbPTyno
WoqonFyTWehJ3IZg/Nw2b5cCAwEAAQ==
-----END PUBLIC KEY-----
"""
